[package]
name = "cicero-tui"
version = "0.1.0"
authors = ["Yan Li <eyeplum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.14"
tui = { version = "0.8", default-features = false, features = ['crossterm'] }

[dependencies.unic]
git = "https://github.com/eyeplum/rust-unic.git"
branch = "develop"
