[package]
name = "cicero-tui"
version = "0.1.0"
authors = ["Yan Li <eyeplum@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.17"
font-kit = "0.7"
pathfinder_geometry = "0.5"
scopeguard = "1.1"

[dependencies.tui]
version = "0.9"
default-features = false
features = ["crossterm"]

[dependencies.unic]
git = "https://github.com/eyeplum/rust-unic.git"
branch = "develop"

[target.'cfg(unix)'.dependencies]
servo-fontconfig = "0.4"
