[package]
name = "cicero-tui"
version = "0.1.0"
authors = ["Yan Li <eyeplum@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
crossterm = "0.17"
freetype-rs = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
servo-fontconfig = "0.5"
scopeguard = "1.1"

[dependencies.tui]
version = "0.9"
default-features = false
features = ["crossterm"]

[dependencies.unic]
git = "https://github.com/eyeplum/rust-unic.git"
branch = "develop"
