name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
    - name: (macOS only) Install fontconfig with Homebrew
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install pkg-config fontconfig
        pkg-config --libs --static fontconfig
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
